---
permalink: 'admin/config.yml'
---
backend:
  name: github
  branch: new
  repo: stardoom4/CE40

media_folder: "public/img"
public_folder: "public"

site_url: https://garud.netlify.app

collections:
  - name: "articles"
    label: "Article"
    folder: "src/posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}  
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "bookmarks"
    label: "Bookmark"
    folder: "src/bookmarks/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Title", name: "title", widget: "string"} 
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}